---
- hosts: ROUTER
  gather_facts: no

  tasks:

   - name: Get running config
     ios_command:
       commands: show run
     register: show_run

   - name: Save config to file
     copy:
       content: "{{ show_run.stdout[0] }}"
       dest: "backup/{{inventory_hostname}} - {{ lookup('pipe', 'date +%Y-%m-%d-%H%M') }}txt" #this add timestamp#
