---
- hosts: R1
  gather_facts: no

  tasks:

   - name: Get running config
     ios_command:
       commands:

         - wr

- hosts: R2
  gather_facts: no

  tasks:

   - name: Get running config
     ios_command:
       commands:

         - wr

- hosts: R3
  gather_facts: no

  tasks:

   - name: Get running config
     ios_command:
       commands:

         - wr

- hosts: R4
  gather_facts: no

  tasks:

   - name: Get running config
     ios_command:
       commands:

         - wr
